import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";
import { api } from "~/utils/api";

const Home: NextPage = () => {  
  return (
    <>
      <Head>
        <title>Global forces 🌎</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        עמוד בית
      </main>
    </>
  );
};

export default Home;
