import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {  
  return (
    <>
      <Head>
        <title>Global forces 🌎</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        עמוד בית
      </main>
    </>
  );
};

export default Home;
